<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $admin = Role::create(['name' => 'Admin']);
        $cashier = Role::create(['name' => 'Cashier']);
        $client = Role::create(['name' => 'Client']);
    
      
        Permission::create(['name'=>'users.index']);
        Permission::create(['name'=>'users.create']);
        Permission::create(['name'=>'users.store']);
        Permission::create(['name'=>'users.show']);
        Permission::create(['name'=>'users.edit']);
        Permission::create(['name'=>'users.update']);
        Permission::create(['name'=>'users.destroy']);
        Permission::create(['name'=>'home']);
        Permission::create(['name'=>'brands.index']);
        Permission::create(['name'=>'brands.create']);
        Permission::create(['name'=>'brands.store']);
        Permission::create(['name'=>'brands.edit']);
        Permission::create(['name'=>'brands.update']);
        Permission::create(['name'=>'brands.destroy']);
        Permission::create(['name'=>'tags.index']);
        Permission::create(['name'=>'tags.create']);
        Permission::create(['name'=>'tags.store']);
        Permission::create(['name'=>'tags.edit']);
        Permission::create(['name'=>'tags.update']);
        Permission::create(['name'=>'tags.destroy']);
        Permission::create(['name'=>'categories.index']);
        Permission::create(['name'=>'categories.create']);
        Permission::create(['name'=>'categories.store']);
        Permission::create(['name'=>'categories.show']);
        Permission::create(['name'=>'categories.edit']);
        Permission::create(['name'=>'categories.update']);
        Permission::create(['name'=>'categories.destroy']);
        Permission::create(['name'=>'products.index']);
        Permission::create(['name'=>'products.store']);
        Permission::create(['name'=>'products.show']);
        Permission::create(['name'=>'products.edit']);
        Permission::create(['name'=>'products.update']);
        Permission::create(['name'=>'products.destroy']);
        Permission::create(['name'=>'posts.index']);
        Permission::create(['name'=>'posts.store']);
        Permission::create(['name'=>'posts.show']);
        Permission::create(['name'=>'posts.edit']);
        Permission::create(['name'=>'posts.update']);
        Permission::create(['name'=>'posts.destroy']);
        Permission::create(['name'=>'social_medias.index']);
        Permission::create(['name'=>'social_medias.create']);
        Permission::create(['name'=>'social_medias.store']);
        Permission::create(['name'=>'social_medias.edit']);
        Permission::create(['name'=>'social_medias.update']);
        Permission::create(['name'=>'social_medias.destroy']);
        Permission::create(['name'=>'sliders.index']);
        Permission::create(['name'=>'sliders.store']);
        Permission::create(['name'=>'sliders.edit']);
        Permission::create(['name'=>'sliders.update']);
        Permission::create(['name'=>'sliders.destroy']);
        Permission::create(['name'=>'promotions.index']);
        Permission::create(['name'=>'promotions.create']);
        Permission::create(['name'=>'promotions.store']);
        Permission::create(['name'=>'promotions.edit']);
        Permission::create(['name'=>'promotions.update']);
        Permission::create(['name'=>'promotions.destroy']);
        Permission::create(['name'=>'clients.index']);
        Permission::create(['name'=>'clients.create']);
        Permission::create(['name'=>'clients.store']);
        Permission::create(['name'=>'clients.show']);
        Permission::create(['name'=>'clients.edit']);
        Permission::create(['name'=>'clients.update']);
        Permission::create(['name'=>'clients.destroy']);
        Permission::create(['name'=>'providers.index']);
        Permission::create(['name'=>'providers.create']);
        Permission::create(['name'=>'providers.store']);
        Permission::create(['name'=>'providers.show']);
        Permission::create(['name'=>'providers.edit']);
        Permission::create(['name'=>'providers.update']);
        Permission::create(['name'=>'providers.destroy']);
        Permission::create(['name'=>'roles.index']);
        Permission::create(['name'=>'roles.show']);
        Permission::create(['name'=>'printers.index']);
        Permission::create(['name'=>'printers.update']);
        Permission::create(['name'=>'orders.index']);
        Permission::create(['name'=>'orders.show']);
        Permission::create(['name'=>'sales.index']);
        Permission::create(['name'=>'sales.create']);
        Permission::create(['name'=>'sales.store']);
        Permission::create(['name'=>'sales.show']);
        Permission::create(['name'=>'purchases.index']);
        Permission::create(['name'=>'purchases.create']);
        Permission::create(['name'=>'purchases.store']);
        Permission::create(['name'=>'purchases.show']);
        Permission::create(['name'=>'business.index']);
        Permission::create(['name'=>'business.update']);
        Permission::create(['name'=>'subscriptions.index']);
        Permission::create(['name'=>'subscriptions.destroy']);
        Permission::create(['name'=>'update_product_status']);
        Permission::create(['name'=>'mark_all_notifications']);
        Permission::create(['name'=>'mark_a_notification']);
        Permission::create(['name'=>'update_profile']);
        Permission::create(['name'=>'orders_update']);
        Permission::create(['name'=>'reports.day']);
        Permission::create(['name'=>'reports.date']);
        Permission::create(['name'=>'report.results']);
        Permission::create(['name'=>'upload.image']);
        Permission::create(['name'=>'upload_images_product']);
        Permission::create(['name'=>'get.images']);
        Permission::create(['name'=>'file.delete']);
        Permission::create(['name'=>'purchases.pdf']);
        Permission::create(['name'=>'sales.pdf']);
        Permission::create(['name'=>'sales.print']);
        Permission::create(['name'=>'upload.purchases']);
        Permission::create(['name'=>'change.status.products']);
        Permission::create(['name'=>'change.status.purchases']);
        Permission::create(['name'=>'change.status.sales']);
        Permission::create(['name'=>'get_products_by_barcode']);
        Permission::create(['name'=>'get_products_by_id']);
        Permission::create(['name'=>'print_barcode']);
        Permission::create(['name'=>'get_subcategories']);
        Permission::create(['name'=>'get_products_by_subcategory']);
        Permission::create(['name'=>'pay']);
        Permission::create(['name'=>'approval']);
        Permission::create(['name'=>'cancelled']);
        Permission::create(['name'=>'web.my_account']);
        Permission::create(['name'=>'web.checkout']);
        Permission::create(['name'=>'web.orders']);
        Permission::create(['name'=>'web.order_details']);
        Permission::create(['name'=>'web.account_info']);
        Permission::create(['name'=>'web.address_edit']);
        Permission::create(['name'=>'web.change_password']);
        Permission::create(['name'=>'web.rate_product']);
        Permission::create(['name'=>'web.update_client']);
        Permission::create(['name'=>'web.update_password']);

        
        $admin->givePermissionTo([
            'users.index',
            'users.create',
            'users.store',
            'users.show',
            'users.edit',
            'users.update',
            'users.destroy',
            'home',
            'brands.index',
            'brands.create',
            'brands.store',
            'brands.edit',
            'brands.update',
            'brands.destroy',
            'tags.index',
            'tags.create',
            'tags.store',
            'tags.edit',
            'tags.update',
            'tags.destroy',
            'categories.index',
            'categories.create',
            'categories.store',
            'categories.show',
            'categories.edit',
            'categories.update',
            'categories.destroy',
            'products.index',
            'products.store',
            'products.show',
            'products.edit',
            'products.update',
            'products.destroy',
            'posts.index',
            'posts.store',
            'posts.show',
            'posts.edit',
            'posts.update',
            'posts.destroy',
            'social_medias.index',
            'social_medias.create',
            'social_medias.store',
            'social_medias.edit',
            'social_medias.update',
            'social_medias.destroy',
            'sliders.index',
            'sliders.store',
            'sliders.edit',
            'sliders.update',
            'sliders.destroy',
            'promotions.index',
            'promotions.create',
            'promotions.store',
            'promotions.edit',
            'promotions.update',
            'promotions.destroy',
            'clients.index',
            'clients.create',
            'clients.store',
            'clients.show',
            'clients.edit',
            'clients.update',
            'clients.destroy',
            'providers.index',
            'providers.create',
            'providers.store',
            'providers.show',
            'providers.edit',
            'providers.update',
            'providers.destroy',
            'roles.index',
            'roles.show',
            'printers.index',
            'printers.update',
            'orders.index',
            'orders.show',
            'sales.index',
            'sales.create',
            'sales.store',
            'sales.show',
            'purchases.index',
            'purchases.create',
            'purchases.store',
            'purchases.show',
            'business.index',
            'business.update',
            'subscriptions.index',
            'subscriptions.destroy',
            'update_product_status',
            'mark_all_notifications',
            'mark_a_notification',
            'update_profile',
            'orders_update',
            'reports.day',
            'reports.date',
            'report.results',
            'upload.image',
            'upload_images_product',
            'get.images',
            'file.delete',
            'purchases.pdf',
            'sales.pdf',
            'sales.print',
            'upload.purchases',
            'change.status.products',
            'change.status.purchases',
            'change.status.sales',
            'get_products_by_barcode',
            'get_products_by_id',
            'print_barcode',
            'get_subcategories',
            'get_products_by_subcategory',
            'pay',
            'approval',
            'cancelled',
            'web.my_account',
            'web.checkout',
            'web.orders',
            'web.order_details',
            'web.account_info',
            'web.address_edit',
            'web.change_password',
            'web.rate_product',
            'web.update_client',
            'web.update_password'
        ]);

        $cashier->givePermissionTo([
            'home',
            'clients.index',
            'clients.create',
            'clients.store',
            'clients.show',
            'clients.edit',
            'clients.update',
            'clients.destroy',
			'orders.index',
            'orders.show',
			'sales.index',
            'sales.create',
            'sales.store',
            'sales.show',
            'purchases.index',
            'purchases.create',
            'purchases.store',
            'purchases.show',
			'update_product_status',
            'mark_all_notifications',
            'mark_a_notification',
			'orders_update',
			'reports.day',
            'reports.date',
            'report.results',
			'purchases.pdf',
			'sales.pdf',
            'sales.print',
			'upload.purchases',
			'change.status.purchases',
			'change.status.sales',
			'get_products_by_barcode',
            'get_products_by_id',
			'print_barcode',
        ]);

        $client->givePermissionTo([
            'pay',
            'approval',
            'cancelled',
            'web.my_account',
            'web.checkout',
            'web.orders',
            'web.order_details',
            'web.account_info',
            'web.address_edit',
            'web.change_password',
            'web.rate_product',
            'web.update_client',
            'web.update_password'
        ]);

        $admin_user = User::create([
            'name'=>'Admin',
            'email'=>'Admin@gmail.com',
            'password'=>'$2y$10$o.CnHSqHSCQ7qSj4zlJU7u0N1QiKqrIjJ2bLP8j/wdw3W8NCA3DkK',
        ]);
        $admin_user->profile()->create();
        $admin_user->assignRole('Admin');

        $cashier_user = User::create([
            'name'=>'Cashier',
            'email'=>'Cashier@gmail.com',
            'password'=>'$2y$10$o.CnHSqHSCQ7qSj4zlJU7u0N1QiKqrIjJ2bLP8j/wdw3W8NCA3DkK',
        ]);
        $cashier_user->profile()->create();
        $cashier_user->assignRole('Cashier');

        $client_user = User::create([
            'name'=>'Client',
            'email'=>'Client@gmail.com',
            'password'=>'$2y$10$o.CnHSqHSCQ7qSj4zlJU7u0N1QiKqrIjJ2bLP8j/wdw3W8NCA3DkK',
        ]);
        $client_user->profile()->create();
        $client_user->assignRole('Client');
        
    }
}
